import { colors, fontSizes, radii, shadows, spacing, typography } from "@/constants/autodaddy";
import { Platform, StyleSheet } from "react-native";

export const carOwnerHomeStyles = StyleSheet.create({
  shell: { flex: 1 },
  scrollContent: {},
  headerBlock: {
    paddingHorizontal: spacing.screenHorizontal,
    paddingBottom: spacing.xs,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 56,
    paddingVertical: 6,
  },
  contentNetworkStrip: {
    marginHorizontal: spacing.screenHorizontal,
    marginBottom: spacing.sm,
  },
  headerIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.55)",
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.18)",
  },
  unreadDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.danger,
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  headerTitle: { fontSize: fontSizes.xl, fontWeight: "900", color: colors.successDark },

  hero: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.screenHorizontal,
    paddingBottom: spacing.lg,
  },
  welcomeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: spacing.xs,
    paddingTop: spacing.sm,
  },
  welcomeTextCol: { gap: 2, alignItems: 'center', width: '80%' },
  welcomeSmall: { color: "rgba(22,101,52,0.85)", fontSize: 23, fontWeight: "800" },
  welcomeName: { color: 'purple', textAlign: 'center', fontSize: 26, fontWeight: "900" },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.7)",
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.18)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  thoughtCard: {
    marginTop: spacing.lg,
    borderRadius: radii.hero,
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.16)",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        backgroundColor: "rgba(255,255,255,0.72)",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: {
        backgroundColor: "#F4FBF6",
      },
    }),
  },
  thoughtCardInner: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  thoughtCardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  thoughtCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSizes.md,
    fontWeight: "900",
    color: colors.successDark,
  },
  thoughtCardHeaderCount: {
    fontSize: fontSizes.xs,
    fontWeight: "800",
    color: colors.textMuted,
    marginRight: 4,
  },
  thoughtCardQuote: {
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: "rgba(22,101,52,0.10)",
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: "rgba(22,101,52,0.88)",
    lineHeight: 22,
    fontStyle: "italic",
  },
  thoughtCardFooter: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(22,101,52,0.10)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  thoughtLikeActions: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  thoughtLikeBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.18)",
    backgroundColor: "rgba(255,255,255,0.65)",
  },
  thoughtLikeBtnActive: {
    backgroundColor: "rgba(22,101,52,0.12)",
    borderColor: "rgba(22,101,52,0.35)",
  },
  thoughtLikeBtnDisabled: { opacity: 0.45 },
  thoughtLikeCount: {
    fontSize: fontSizes.sm,
    fontWeight: "800",
    color: colors.textMuted,
    flexShrink: 1,
    textAlign: "right",
  },

  contentPad: {
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: spacing.lg,
    gap: spacing.lg,
  },

  pressablePressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  pressableHover: {
    transform: [{ scale: 1.02 }],
  },
  recoPressed: {
    opacity: 0.96,
    transform: [{ scale: 0.995 }],
  },
  section: { gap: spacing.md },
  sectionTitle: {
    ...typography.cardTitle,
    fontSize: fontSizes.lg,
    color: colors.text,
  },

  actionGrid: { gap: spacing.md },
  actionRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.md,
  },
  actionCell: { flex: 1, minWidth: 0 },
  actionTile: {
    width: "100%",
    minWidth: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minHeight: 132,
    ...(Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }) as object),
  },
  actionIcon: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: "#E8F5E9",
    alignItems: "center",
    justifyContent: "center",
  },
  actionLabel: {
    textAlign: "center",
    color: "#1A1A1A",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "900",
    includeFontPadding: false,
  },

  statsRow: { flexDirection: "row", gap: spacing.sm },
  statCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: spacing.md,
    ...shadows.card,
  },
  statTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: colors.successMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  statLabel: { color: colors.textMuted, fontSize: fontSizes.sm, fontWeight: "800" },
  statValue: { marginTop: 8, fontSize: 22, fontWeight: "900", color: colors.text },
  statSub: { marginTop: 2, fontSize: fontSizes.sm, fontWeight: "800", color: colors.successDark },

  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: spacing.md,
    ...(Platform.OS === "android" ? ({ elevation: 2 } as object) : shadows.card),
  },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.sm },
  cardTitle: { ...typography.cardTitle, fontSize: fontSizes.lg, color: colors.text },

  nextServiceRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  nextServiceLeft: { flex: 1, minWidth: 0 },
  nextServiceBig: { fontSize: 25, fontWeight: "900", color: colors.successDark },
  nextServiceLine: { marginTop: 2, fontSize: fontSizes.md, fontWeight: "900", color: colors.text },
  nextServiceSub: { marginTop: 2, fontSize: fontSizes.sm, fontWeight: "700", color: colors.textMuted },
  nextServicePlateLabel: {
    marginTop: spacing.sm,
    fontSize: fontSizes.xs,
    fontWeight: "800",
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  nextServicePlate: {
    marginTop: 4,
    fontSize: fontSizes.lg,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: 0.5,
  },
  nextServiceVehicle: {
    marginTop: spacing.xs,
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: colors.textMuted,
    textTransform: "uppercase",
  },
  nextServiceItem: {
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  nextServiceItemFirst: {
    marginTop: spacing.lg,
  },
  nextServiceItemName: {
    fontSize: fontSizes.md,
    fontWeight: "900",
    color: colors.text,
  },
  nextServiceItemDesc: {
    marginTop: 4,
    fontSize: fontSizes.sm,
    fontWeight: "600",
    color: colors.textMuted,
    lineHeight: 20,
  },
  nextServiceIssueBlock: { marginTop: spacing.md },
  nextServiceIssueLabel: {
    fontSize: fontSizes.xs,
    fontWeight: "800",
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  nextServiceIssue: {
    marginTop: 4,
    fontSize: fontSizes.sm,
    fontWeight: "600",
    color: colors.text,
    lineHeight: 20,
  },
  carArt: {
    width: 92,
    height: 62,
    borderRadius: 16,
    backgroundColor: colors.primaryMutedBg,
    alignItems: "center",
    justifyContent: "center",
  },
  miniRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md },
  miniPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: radii.round,
    backgroundColor: colors.bgAlt,
  },
  miniPillText: { fontSize: fontSizes.sm, fontWeight: "800", color: colors.textMuted },

  apptTitle: { fontSize: fontSizes.lg, fontWeight: "900", color: colors.text },
  progressRow: { marginTop: spacing.sm, gap: 8 },
  progressLabel: { fontSize: fontSizes.sm, fontWeight: "800", color: colors.textMuted },
  progressTrack: { height: 10, borderRadius: radii.round, backgroundColor: colors.trackBg, overflow: "hidden" },
  progressFill: { width: "66%", height: "100%", backgroundColor: colors.success, borderRadius: radii.round },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.sm },
  recoRow: { flexDirection: "row", gap: spacing.sm, alignItems: "center", paddingVertical: spacing.sm },
  recoIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: colors.primaryMutedBg,
    alignItems: "center",
    justifyContent: "center",
  },
  recoTitle: { fontSize: fontSizes.md, fontWeight: "900", color: colors.text },
  recoSub: { marginTop: 2, fontSize: fontSizes.sm, fontWeight: "700", color: colors.textMuted },

  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.successMuted,
    borderTopWidth: 1,
    borderTopColor: "rgba(22,101,52,0.18)",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-around",
    ...(Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -1 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }) as object),
  },
  bottomTab: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
});
