import { colors, fontSizes, shadows, spacing, typography } from "@/constants/autodaddy";
import { StyleSheet } from "react-native";

export const carOwnerProfileStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: spacing.md,
    ...shadows.card,
  },
  cardSavingRow: { alignItems: "flex-end", marginBottom: spacing.sm },
  photoLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    marginTop: -spacing.xs,
  },
  photoLinkText: {
    fontSize: fontSizes.sm,
    fontWeight: "800",
    color: colors.successDark,
  },

  loadingWrap: { paddingVertical: spacing.lg, alignItems: "center", gap: spacing.sm },
  loadingText: { ...typography.bodyMuted },

  field: { marginTop: spacing.md },
  fieldLabelRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  fieldIcon: {
    width: 26,
    height: 26,
    borderRadius: 10,
    backgroundColor: colors.successMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  fieldLabel: { fontSize: fontSizes.sm, fontWeight: "900", color: colors.textMuted },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgAlt,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: fontSizes.md,
    fontWeight: "800",
    color: colors.text,
  },
  inputRowWrap: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgAlt,
    borderRadius: 14,
    minHeight: 44,
    paddingLeft: 8,
    paddingRight: 12,
  },
  inputRowField: {
    flex: 1,
    paddingVertical: 10,
    fontSize: fontSizes.md,
    fontWeight: "800",
    color: colors.text,
  },
  inputRowWrapError: {
    borderColor: colors.danger,
    backgroundColor: colors.dangerMuted,
  },
  inputError: {
    borderColor: colors.danger,
    backgroundColor: colors.dangerMuted,
  },
  inputMultiline: { minHeight: 80, textAlignVertical: "top" },
  fieldErrorText: {
    marginTop: 6,
    fontSize: fontSizes.xs,
    fontWeight: "700",
    color: colors.danger,
  },
  readOnlyBox: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "rgba(220,230,246,0.9)",
    backgroundColor: "rgba(255,255,255,0.75)",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    justifyContent: "center",
  },
  readOnlyBoxMultiline: { minHeight: 80, justifyContent: "flex-start" },
  readOnlyText: { fontSize: fontSizes.md, fontWeight: "800", color: colors.text },

  selectRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgAlt,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 44,
  },
  selectRowPressed: { opacity: 0.92 },
  selectRowDisabled: { opacity: 0.55 },
  selectRowText: { flex: 1, fontSize: fontSizes.md, fontWeight: "800", color: colors.text },
  selectRowPlaceholder: { color: colors.textLight, fontWeight: "700" },

  saveActionsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  cancelBtn: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  cancelBtnText: { fontSize: fontSizes.md, fontWeight: "900", color: colors.text },
  saveBtn: {
    flex: 1,
    backgroundColor: colors.successDark,
    borderRadius: 16,
    paddingVertical: spacing.md,
    alignItems: "center",
  },
  saveBtnText: { color: colors.white, fontSize: fontSizes.md, fontWeight: "900" },
});
