import { colors, fontSizes, radii, spacing } from "@/constants/autodaddy";
import { Platform, StyleSheet } from "react-native";

export const addVehicleFormStyles = StyleSheet.create({
  content: {
    gap: spacing.md,
  },
  heroCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    backgroundColor: colors.white,
    borderRadius: radii.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroIcon: {
    width: 46,
    height: 46,
    borderRadius: 18,
    backgroundColor: colors.successMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: { fontSize: fontSizes.xl, fontWeight: "900", color: colors.text },
  heroSub: { marginTop: 2, fontSize: fontSizes.sm, color: colors.textMuted, fontWeight: "600" },
  card: {
    backgroundColor: colors.white,
    borderRadius: radii.xl,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: { fontSize: fontSizes.lg, fontWeight: "900", color: colors.text },
  fieldWrap: { gap: spacing.sm - 2 },
  fieldLabel: { fontSize: fontSizes.md, fontWeight: "700", color: colors.text },
  inputWrap: {
    minHeight: 42,
    borderRadius: radii.md,
    backgroundColor: "#F1F4FA",
    borderWidth: 1,
    borderColor: "#D9DFEA",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    gap: spacing.sm,
  },
  input: {
    flex: 1,
    fontSize: fontSizes.md,
    color: colors.text,
    paddingVertical: Platform.OS === "ios" ? spacing.sm : spacing.xs,
  },
  errorText: { marginTop: 4, color: colors.danger, fontSize: fontSizes.xs, fontWeight: "700" },
  twoCols: { flexDirection: "row", gap: spacing.sm },
  col: { flex: 1 },
  imageRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  imagePickBtn: {
    flex: 1,
    minHeight: 54,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#CBE7D4",
    backgroundColor: "#F0FDF4",
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  imagePickTitle: { fontSize: fontSizes.md, fontWeight: "800", color: colors.text },
  imagePickSub: { marginTop: 2, fontSize: fontSizes.xs, fontWeight: "700", color: colors.textMuted },
  existingImagesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  existingImageTile: {
    width: "48%",
    aspectRatio: 1.25,
    borderRadius: radii.lg,
    overflow: "hidden",
    backgroundColor: colors.bgAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  existingImage: { width: "100%", height: "100%" },
  existingImageLabel: {
    position: "absolute",
    left: 8,
    bottom: 8,
    borderRadius: radii.round,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  existingImageLabelText: { color: colors.white, fontSize: fontSizes.xs, fontWeight: "900" },
  editPhotoHint: { color: colors.textMuted, fontSize: fontSizes.sm, fontWeight: "700", lineHeight: 20 },
  removeImageBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.dangerMuted,
  },
  carImagesBtn: {
    minHeight: 54,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#CBE7D4",
    backgroundColor: "#F0FDF4",
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  clearCarImagesBtn: { alignSelf: "flex-start", paddingVertical: spacing.xs, paddingHorizontal: spacing.sm },
  clearCarImagesText: { color: colors.danger, fontSize: fontSizes.sm, fontWeight: "800" },
  saveBtn: {
    minHeight: 52,
    borderRadius: radii.xl,
    backgroundColor: colors.successDark,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.sm,
  },
  saveBtnDisabled: { opacity: 0.65 },
  saveText: { color: colors.white, fontSize: fontSizes.base, fontWeight: "900" },
});
