import { colors, fontSizes, radii, shadows, spacing, typography } from "@/constants/autodaddy";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screenContent: {
    gap: spacing.lg,
    // `CarOwnerStackScreenFrame` already applies safe-area bottom padding.
    // Defining `paddingBottom` here overrides it and can cause the last card
    // to sit behind the device navigation/gesture area.
  },
  headerCard: {
    borderRadius: 26,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.14)",
    ...shadows.card,
  },
  heroTopRow: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  heroCopy: { flex: 1, gap: 2 },
  icon: {
    width: 54,
    height: 54,
    borderRadius: 22,
    backgroundColor: "rgba(22,101,52,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.14)",
  },
  eyebrow: {
    fontSize: fontSizes.xs,
    fontWeight: "900",
    letterSpacing: 0.8,
    color: colors.successDark,
    textTransform: "uppercase",
  },
  refreshBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.14)",
  },
  addHeroBtn: {
    marginTop: spacing.xl,
    minHeight: 50,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    backgroundColor: colors.successDark,
  },
  addHeroText: { color: colors.white, fontSize: fontSizes.base, fontWeight: "900" },
  title: { ...typography.cardTitle, color: colors.text, fontSize: fontSizes.display },
  subtitle: { ...typography.bodyMuted, marginTop: 4, lineHeight: 21 },

  loadingWrap: {
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadingText: { fontSize: fontSizes.sm, fontWeight: "800", color: colors.textMuted },
  emptyCard: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 26,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 26,
    backgroundColor: colors.successMuted,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  emptyTitle: { fontSize: fontSizes.xl, fontWeight: "900", color: colors.text, textAlign: "center" },
  emptySub: { ...typography.bodyMuted, marginTop: spacing.xs, textAlign: "center", lineHeight: 21 },
  emptyBtn: {
    marginTop: spacing.lg,
    minHeight: 46,
    paddingHorizontal: spacing.xl,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    backgroundColor: colors.successDark,
  },
  emptyBtnText: { color: colors.white, fontSize: fontSizes.sm, fontWeight: "900" },

  sectionHeader: {
    marginTop: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: { fontSize: fontSizes.xl, fontWeight: "900", color: colors.text },
  sectionCount: {
    overflow: "hidden",
    borderRadius: radii.round,
    paddingHorizontal: spacing.md,
    paddingVertical: 7,
    backgroundColor: colors.successMuted,
    color: colors.successDark,
    fontSize: fontSizes.xs,
    fontWeight: "900",
  },
  list: { gap: spacing.lg },
  vehicleCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.12)",
    ...shadows.card,
  },
  vehicleGalleryOuter: {
    overflow: "hidden",
    backgroundColor: "#F1F5F9",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15,23,42,0.08)",
  },
  vehicleGalleryPlaceholder: {
    width: "100%",
    aspectRatio: 16 / 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  collapsedRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.sm,
    gap: spacing.md,
    minHeight: 76,
  },
  collapsedThumb: {
    width: 72,
    height: 72,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  collapsedThumbImg: {
    width: "100%",
    height: "100%",
  },
  collapsedPlate: {
    flex: 1,
    fontSize: fontSizes.lg,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: 0.3,
  },
  collapsedChevBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.successMuted,
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.14)",
  },
  plateBar: {
    backgroundColor: colors.successDark,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
  },
  plateBarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    backgroundColor: colors.successDark,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
  },
  plateBarChevBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  plateText: {
    flex: 1,
    color: colors.white,
    fontSize: fontSizes.lg,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  cardBody: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.md,
  },
  badgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  detailBadge: {
    width: "48%",
    flexGrow: 1,
    flexBasis: "46%",
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: radii.round,
    backgroundColor: colors.successMuted,
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.12)",
  },
  detailBadgeFull: {
    width: "100%",
    flexBasis: "100%",
  },
  detailBadgeText: {
    fontSize: fontSizes.sm,
    fontWeight: "800",
    color: colors.successDark,
  },
  detailBadgePlaceholder: {
    color: "rgba(22,101,52,0.55)",
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  footerIconBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  footerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  vehicleGallerySlide: { overflow: "hidden" },
  vehicleGalleryImg: { width: "100%", height: "100%" },
  vehicleGalleryDots: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
  },
  vehicleGalleryDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(15,23,42,0.18)",
  },
  vehicleGalleryDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.successDark,
  },
  expandWrap: { gap: spacing.sm },
  paths: { gap: spacing.sm },
  pathRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: "#F8FBFF",
    borderWidth: 1,
    borderColor: colors.border,
  },
  pathLabel: { width: 92, fontSize: fontSizes.xs, fontWeight: "900", color: colors.textMuted },
  pathValue: { flex: 1, fontSize: fontSizes.sm, fontWeight: "800", color: colors.text, flexWrap: "wrap" },
  primaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.successDark,
    borderRadius: 18,
    paddingVertical: spacing.lg,
  },
  primaryBtnText: { color: colors.white, fontSize: fontSizes.sm, fontWeight: "900" },
  secondaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.successMuted,
    borderRadius: 18,
    paddingVertical: spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(22,101,52,0.18)",
  },
  secondaryBtnText: { color: colors.successDark, fontSize: fontSizes.sm, fontWeight: "900" },

  viewerBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.82)", justifyContent: "flex-end" },
  viewerSheet: { backgroundColor: "transparent", borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: "hidden" },
  viewerSheetBg: { flex: 1 },
  viewerHandleWrap: {
    paddingTop: 10,
    paddingBottom: 6,
    alignItems: "center",
    backgroundColor: "transparent",
  },
  viewerHandle: {
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  viewerTopBar: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
    minHeight: 64,
  },
  viewerTitle: { color: colors.white, fontSize: fontSizes.lg, fontWeight: "900", flex: 1, paddingRight: spacing.sm },
  viewerTopActions: { flexDirection: "row", alignItems: "center", gap: 10, marginLeft: spacing.sm },
  viewerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  viewerIconBtnDisabled: { opacity: 0.35 },
  viewerClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  viewerBottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 22,
    paddingTop: 14,
    paddingBottom: 6,
    paddingHorizontal: spacing.md,
  },
  viewerBottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-around" },
  viewerIndexPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  viewerIndexPillText: { color: colors.white, fontSize: fontSizes.md, fontWeight: "900" },
  viewerPage: { alignItems: "center", justifyContent: "center" },
  viewerList: { flex: 1, backgroundColor: "transparent" },
  viewerImageBox: {
    width: "94%",
    height: "90%",
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.22)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  viewerImageWrap: { width: "100%", height: "100%" },
  viewerImage: { width: "100%", height: "100%" },
});
