import DummyUserListPage, { type DummyUserListConfig } from "./DummyUserListPage";

const ASSOCIATES_CONFIG: DummyUserListConfig = {
  title: "Associates",
  deletedTitle: "Deleted Associates",
  addLabel: "New Associate",
  roleLabel: "associate",
  primaryFieldLabel: "Company",
  regionFieldLabel: "Region",
  countALabel: "Referrals",
  countBLabel: "Linked Shops",
  exportFilePrefix: "associates",
  columns: [
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "primary", label: "Company" },
    { key: "city", label: "City" },
    { key: "region", label: "Region" },
    { key: "date", label: "Date" },
    { key: "countA", label: "Referrals" },
    { key: "countB", label: "Linked Shops" },
    { key: "status", label: "Status" },
  ],
  defaultVisible: ["name", "phone", "primary", "city", "region", "date", "countA", "countB", "status"],
  initialData: [
    {
      _id: "assoc-1",
      name: "Sarah Mitchell",
      email: "sarah.mitchell@northbridge.ca",
      countryCode: "+1",
      phone: "7059913785",
      pincode: "P3E 5H1",
      address: "42 Elm Street",
      city: "Sudbury",
      region: "Northern Ontario",
      createdAt: "2026-01-12T10:00:00.000Z",
      isDisabled: false,
      primaryLabel: "NorthBridge Auto Partners",
      countA: 18,
      countB: 6,
    },
    {
      _id: "assoc-2",
      name: "James Chen",
      email: "j.chen@maplefleet.com",
      countryCode: "+1",
      phone: "4165550192",
      pincode: "M5V 2T6",
      address: "88 Bay Street, Suite 210",
      city: "Toronto",
      region: "GTA",
      createdAt: "2026-02-03T14:30:00.000Z",
      isDisabled: false,
      primaryLabel: "Maple Fleet Services",
      countA: 24,
      countB: 9,
    },
    {
      _id: "assoc-3",
      name: "Priya Sharma",
      email: "priya@driveconnect.ca",
      countryCode: "+1",
      phone: "6045550147",
      pincode: "V6B 1A1",
      address: "1200 West Georgia St",
      city: "Vancouver",
      region: "British Columbia",
      createdAt: "2026-02-18T09:15:00.000Z",
      isDisabled: true,
      primaryLabel: "DriveConnect BC",
      countA: 11,
      countB: 4,
    },
    {
      _id: "assoc-4",
      name: "Marcus Dubois",
      email: "marcus@quebecmotors.qc.ca",
      countryCode: "+1",
      phone: "5145550188",
      pincode: "H3B 4W8",
      address: "500 Rue Sainte-Catherine",
      city: "Montreal",
      region: "Quebec",
      createdAt: "2026-03-05T11:45:00.000Z",
      isDisabled: false,
      primaryLabel: "Quebec Motors Alliance",
      countA: 31,
      countB: 12,
    },
    {
      _id: "assoc-5",
      name: "Emily Watson",
      email: "emily.watson@prairieauto.ca",
      countryCode: "+1",
      phone: "4035550163",
      pincode: "T2P 1J9",
      address: "200 8 Ave SW",
      city: "Calgary",
      region: "Alberta",
      createdAt: "2026-03-22T16:20:00.000Z",
      isDisabled: false,
      primaryLabel: "Prairie Auto Network",
      countA: 9,
      countB: 3,
    },
    {
      _id: "assoc-6",
      name: "David Okonkwo",
      email: "d.okonkwo@atlanticpartners.ca",
      countryCode: "+1",
      phone: "9025550134",
      pincode: "B3J 1S9",
      address: "1800 Argyle Street",
      city: "Halifax",
      region: "Atlantic Canada",
      createdAt: "2026-04-08T08:00:00.000Z",
      isDisabled: false,
      primaryLabel: "Atlantic Auto Partners",
      countA: 14,
      countB: 5,
    },
    {
      _id: "assoc-7",
      name: "Lisa Tremblay",
      email: "lisa.t@ottawadrive.ca",
      countryCode: "+1",
      phone: "6135550171",
      pincode: "K1P 5M7",
      address: "99 Bank Street",
      city: "Ottawa",
      region: "Eastern Ontario",
      createdAt: "2026-04-25T13:10:00.000Z",
      isDisabled: false,
      primaryLabel: "Ottawa Drive Group",
      countA: 7,
      countB: 2,
    },
    {
      _id: "assoc-8",
      name: "Robert Singh",
      email: "rsingh@windsorconnect.ca",
      countryCode: "+1",
      phone: "5195550156",
      pincode: "N9A 5K6",
      address: "350 Ouellette Avenue",
      city: "Windsor",
      region: "Southwestern Ontario",
      createdAt: "2026-05-10T10:30:00.000Z",
      isDisabled: false,
      status: "deleted",
      primaryLabel: "Windsor Connect Auto",
      countA: 5,
      countB: 1,
    },
  ],
};

export default function Associates() {
  return <DummyUserListPage config={ASSOCIATES_CONFIG} />;
}
