import DummyUserListPage, { type DummyUserListConfig } from "./DummyUserListPage";

const DEALERS_CONFIG: DummyUserListConfig = {
  title: "Dealers",
  deletedTitle: "Deleted Dealers",
  addLabel: "New Dealer",
  roleLabel: "dealer",
  primaryFieldLabel: "Dealership",
  regionFieldLabel: "Province",
  countALabel: "Listings",
  countBLabel: "Leads",
  exportFilePrefix: "dealers",
  columns: [
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "primary", label: "Dealership" },
    { key: "city", label: "City" },
    { key: "region", label: "Province" },
    { key: "date", label: "Date" },
    { key: "countA", label: "Listings" },
    { key: "countB", label: "Leads" },
    { key: "status", label: "Status" },
  ],
  defaultVisible: ["name", "phone", "primary", "city", "region", "date", "countA", "countB", "status"],
  initialData: [
    {
      _id: "dealer-1",
      name: "Michael Brooks",
      email: "mbrooks@lakesidemotors.ca",
      countryCode: "+1",
      phone: "7059912200",
      pincode: "P3A 4R5",
      address: "1500 Lasalle Blvd",
      city: "Sudbury",
      region: "Ontario",
      createdAt: "2026-01-08T09:00:00.000Z",
      isDisabled: false,
      primaryLabel: "Lakeside Motors",
      countA: 42,
      countB: 16,
    },
    {
      _id: "dealer-2",
      name: "Angela Foster",
      email: "a.foster@citywheels.ca",
      countryCode: "+1",
      phone: "4165550288",
      pincode: "M4B 1B3",
      address: "2200 Danforth Avenue",
      city: "Toronto",
      region: "Ontario",
      createdAt: "2026-01-20T11:30:00.000Z",
      isDisabled: false,
      primaryLabel: "City Wheels Auto Sales",
      countA: 67,
      countB: 28,
    },
    {
      _id: "dealer-3",
      name: "Kevin Lau",
      email: "klau@pacificdrive.ca",
      countryCode: "+1",
      phone: "6045550299",
      pincode: "V5Z 2M9",
      address: "4500 Kingsway",
      city: "Burnaby",
      region: "British Columbia",
      createdAt: "2026-02-14T15:00:00.000Z",
      isDisabled: false,
      primaryLabel: "Pacific Drive Motors",
      countA: 53,
      countB: 21,
    },
    {
      _id: "dealer-4",
      name: "Sophie Martin",
      email: "sophie@autostar.qc.ca",
      countryCode: "+1",
      phone: "5145550311",
      pincode: "H1A 0A1",
      address: "8000 Boulevard Henri-Bourassa",
      city: "Montreal",
      region: "Quebec",
      createdAt: "2026-03-01T10:15:00.000Z",
      isDisabled: true,
      primaryLabel: "AutoStar Quebec",
      countA: 38,
      countB: 12,
    },
    {
      _id: "dealer-5",
      name: "Thomas Reid",
      email: "treid@prairiemotors.ca",
      countryCode: "+1",
      phone: "3065550333",
      pincode: "S7K 3J5",
      address: "210 Circle Drive",
      city: "Saskatoon",
      region: "Saskatchewan",
      createdAt: "2026-03-18T14:45:00.000Z",
      isDisabled: false,
      primaryLabel: "Prairie Motors Ltd",
      countA: 29,
      countB: 9,
    },
    {
      _id: "dealer-6",
      name: "Nadia Hassan",
      email: "n.hassan@capitalcars.ca",
      countryCode: "+1",
      phone: "6135550344",
      pincode: "K2P 0K1",
      address: "75 Gloucester Street",
      city: "Ottawa",
      region: "Ontario",
      createdAt: "2026-04-02T08:30:00.000Z",
      isDisabled: false,
      primaryLabel: "Capital Cars Ottawa",
      countA: 45,
      countB: 19,
    },
    {
      _id: "dealer-7",
      name: "Gregory Walsh",
      email: "gwalsh@maritimemotors.ca",
      countryCode: "+1",
      phone: "9025550355",
      pincode: "B3L 4P3",
      address: "3000 Robie Street",
      city: "Halifax",
      region: "Nova Scotia",
      createdAt: "2026-04-19T12:00:00.000Z",
      isDisabled: false,
      primaryLabel: "Maritime Motors",
      countA: 22,
      countB: 8,
    },
    {
      _id: "dealer-8",
      name: "Jennifer Park",
      email: "j.park@edmontonauto.ca",
      countryCode: "+1",
      phone: "7805550366",
      pincode: "T5J 2R7",
      address: "10200 Jasper Avenue",
      city: "Edmonton",
      region: "Alberta",
      createdAt: "2026-05-05T16:10:00.000Z",
      isDisabled: false,
      status: "deleted",
      primaryLabel: "Edmonton Auto Centre",
      countA: 15,
      countB: 4,
    },
  ],
};

export default function Dealers() {
  return <DummyUserListPage config={DEALERS_CONFIG} />;
}
